// Copyright (c) 2026 MCode
//
// Licensed under either of Apache License, Version 2.0 or MIT License at your option.

//! `mcc proj` — Project skeleton (M1 converged to only keep create)
//!
//! ## Project configuration (M3: single source schema)
//!
//! The `project.toml` at project root is the **only** source of project metadata, schema is
//! fully consistent with `cmds::manifest::Manifest`:
//!
//! ```toml
//! [project]
//! name = "myproj"
//! version = "0.1.0"
//! entry = "src/main.mc"
//! # top_module = "main"
//!
//! [dependencies]
//! mcode = "*"
//! ```
//!
//! `project.toml` generated by `mcc proj create <path>` can be directly consumed by `mcc build` /
//! `mcc parse ./<path>` / `mcc check ./<path>` (zero manual edits).

use crate::cli::ProjAction;
use crate::cmds::manifest::Manifest;
use crate::output::envelope::WorkspaceRef;
use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

// ============================================================================
// Entry point
// ============================================================================

pub fn run(action: &ProjAction) -> Result<()> {
    match action {
        ProjAction::Create { path } => cmd_create(path),
    }
}

// ============================================================================
// Create project
// ============================================================================

fn cmd_create(path: &str) -> Result<()> {
    let root = PathBuf::from(path);

    if root.exists() {
        // Directory already exists
        anyhow::bail!("proj create: directory already exists '{}'", root.display());
    }

    // Project name = directory name
    let name = root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("untitled")
        .to_string();

    let entry_rel = "src/main.mc";

    // Directory skeleton
    fs::create_dir_all(root.join("src"))
        .with_context(|| format!("can't create directory: {}", root.join("src").display()))?;

    // Entry placeholder file (only comments, ensure parseable)
    let entry_abs = root.join(entry_rel);
    fs::write(
        &entry_abs,
        format!(
            "// {name} — created by `mcc proj create`\n// Write MC code here; entry and top module in project.toml\n"
        ),
    )
    .with_context(|| format!("can't write entry file: {}", entry_abs.display()))?;

    // Complete project.toml (single source schema, consistent with Manifest)
    let toml = Manifest::generate_default(&name, entry_rel);
    fs::write(root.join("project.toml"), toml).with_context(|| {
        format!(
            "can't write project.toml: {}",
            root.join("project.toml").display()
        )
    })?;

    eprintln!(
        "✓ project '{}' created at {} (entry: {})",
        name,
        root.display(),
        entry_rel
    );

    Ok(())
}

// ============================================================================
// Helper functions
// ============================================================================

pub fn resolve_workspace_ref() -> WorkspaceRef {
    let (id, kind, _) = mcc::workspace_info();
    match kind.as_str() {
        "Project" => WorkspaceRef::project(id),
        _ => WorkspaceRef::project(id),
    }
}

pub fn active_project_name() -> String {
    let (id, kind, _) = mcc::workspace_info();
    if kind == "Project" {
        id
    } else {
        String::new()
    }
}

pub fn active_project_root() -> Option<String> {
    let (id, kind, root) = mcc::workspace_info();
    if kind == "Project" && !id.is_empty() {
        Some(root)
    } else {
        None
    }
}
