// Copyright (c) 2026 MCode
//
// Licensed under either of Apache License, Version 2.0 or MIT License at your option.

//! Text generation for `import_skeleton`: `project.toml` / `main.mc` / `bom.mc`.
//!
//! Shape mirrors the hand-transcribed reference projects (mcs/g18, mcs/120w):
//! local `component` blocks with `p{n}` stub pins (directions all `io` — psrc/
//! psnk are never guessed), one `in` anchor per net actually referenced, and
//! inline `::CAP/::RES/::IND` chains only for the high-confidence passives the
//! value parser approved. Domains are TODO comment lines only (`::DC(?V)` is
//! not legal code — no live domain guesses).

use super::{CompPlan, MctDesign};
use std::collections::BTreeSet;

/// Files that render_main feeds back to the caller via todo_count.
pub struct Rendered {
    pub main: String,
    pub todo_count: usize,
}

/// `project.toml` — same default shape `mcc manifest new` writes.
pub fn render_project(name: &str) -> String {
    crate::cli::manifest::Manifest::generate_default(name, "main.mc")
}

/// `bom.mc` shell: assembly class (DNP/NC) calls are human semantic
/// decisions — the skeleton does not guess.
pub fn render_bom() -> String {
    "# Copyright (c) 2026 MCode\n\
     # BOM assembly annotations (DNP/NC) - the skeleton carries no calls;\n\
     # transcribe by hand from the netlist.md BOM summary and the drawing\n\
     \n\
     bom main { }\n"
    .to_string()
}

/// `main.mc`: file header (source / attach rate / TODO summary) + class
/// definitions + the main module.
#[allow(clippy::too_many_arguments)]
pub fn render_main(
    d: &MctDesign,
    comps: &[CompPlan],
    net_lines: &[Vec<String>],
    net_idents: &[String],
    net_renamed: &[Option<String>],
    display: &[String],
    used_nets: &BTreeSet<usize>,
    name: &str,
) -> Rendered {
    let mut todos: Vec<String> = Vec::new();
    let rate = d.meta.attach_rate.unwrap_or(0.0);

    // ---------------- file header ----------------
    let mut mc = String::new();
    mc.push_str("# Copyright (c) 2026 MCode\n");
    mc.push_str(&format!(
        "# skeleton: generated by mcc import --skeleton from mct.netlist/1 (tool: {}, project {name})\n",
        d.meta.tool
    ));
    mc.push_str(&format!("# source: {}\n", d.meta.source));
    mc.push_str(&format!("# generated: {} (UTC)\n", today_utc()));
    if rate < 0.85 {
        mc.push_str(&format!(
            "# WARNING: pin attach rate {:.1}% is below 85% - the geometric reconstruction is low-confidence, verify net by net before wiring\n",
            rate * 100.0
        ));
    } else {
        mc.push_str(&format!("# pin attach rate: {:.1}%\n", rate * 100.0));
    }
    mc.push_str(
        "# convention: anything unresolved (values, pin directions, power domains) stays a TODO(import) stub - nothing is invented; the semantic calls are human\n",
    );
    mc.push_str(
        "# (net-name semantics, domain assignment, DNP/NC calls, mcpub library matching are all human work)\n",
    );

    // TODO summary (numbered list; grep "TODO(import)" to walk it)
    for c in comps {
        if let Some(t) = &c.value_todo {
            todos.push(format!("{}: {t}", c.designator));
        }
        if c.gate_todo {
            todos.push(format!(
                "{}: eagle gate dimension not represented (pin names are pin numbers only; same-number pins of different gates would merge) - verify by hand",
                c.designator
            ));
        }
        if c.net_pins.is_empty() {
            // A part absent from every net produces no block/instance (an
            // empty pins block is a hard E2116); the header TODO hands it to
            // a human.
            todos.push(format!(
                "{}: no netted pins (absent from every net) -> no block/instance generated, human to fill in",
                c.designator
            ));
        } else if c.net_pins.len() != 2 && is_passive_libref(&c.libref) {
            todos.push(format!(
                "{}: two-pin part has {} netted pins != 2 (dangling) -> block stub, missing pins to fill in",
                c.designator,
                c.net_pins.len()
            ));
        }
    }
    for di in used_nets {
        let disp = &display[*di];
        if is_domain_candidate(disp) {
            todos.push(format!(
                "net {disp}: power-domain candidate (assumed return pair [{}, GND]) -> the ::DC(?V) value is a human call",
                net_idents[*di]
            ));
        }
    }
    if !d.dangle.is_empty() {
        todos.push(format!(
            "dangling attachment points: {} (see the mct output's dangling section; judge NC vs missing connection per item)",
            d.dangle.len()
        ));
    }
    mc.push_str("#\n# TODO(import) summary:\n");
    if todos.is_empty() {
        mc.push_str("#   (none - all values parsed, no domain candidates, no dangling)\n");
    }
    for (i, t) in todos.iter().enumerate() {
        mc.push_str(&format!("#   {}. {t}\n", i + 1));
    }

    // ---------------- class definitions ----------------
    mc.push_str(
        "\n# ---- class definitions (local components; directions all io, psrc/psnk never guessed) ----\n",
    );
    for c in comps {
        if c.inline.is_some() || c.net_pins.is_empty() {
            continue;
        }
        mc.push_str(&format!("\ncomponent {}\n{{\n", c.class));
        let partno = escape(&c.comment);
        if c.comment.trim().is_empty() {
            mc.push_str(&format!("    partno = \"{}\"\n", escape(&c.designator)));
            mc.push_str(
            "    // TODO(import): empty mct comment - partno falls back to the designator, verify\n",
        );
        } else {
            mc.push_str(&format!("    partno = \"{partno}\"\n"));
        }
        mc.push_str("\n    pins = [\n");
        for (raw, ph) in &c.net_pins {
            // Pin numbers echo the original text; illegal characters fold
            // with a trace (a pin number is a literal label, never guessed).
            let num: String = raw
                .chars()
                .map(|c| if c.is_ascii_alphanumeric() || c == '_' || c == '-' { c } else { '_' })
                .collect();
            if &num == raw {
                mc.push_str(&format!("        io {raw} = {ph}\n"));
            } else {
                mc.push_str(&format!("        io {num} = {ph} // was: {raw}\n"));
            }
        }
        mc.push_str("    ]\n}\n");
    }

    // ---------------- main module ----------------
    mc.push_str("\nmodule main\n{\n");
    mc.push_str("    // ---- instances ----\n");
    for c in comps {
        if c.inline.is_some() || c.net_pins.is_empty() {
            continue;
        }
        mc.push_str(&format!("    {} {}\n", c.class, c.ident));
    }

    mc.push_str(
        "\n    // ---- anchors (one per referenced net; semantics and domain assignment are human) ----\n",
    );
    for k in used_nets {
        let ident = &net_idents[*k];
        let mut line = format!("    in {ident}");
        if let Some(orig) = &net_renamed[*k] {
            line.push_str(&format!(" // was: {orig}"));
        }
        if is_domain_candidate(&display[*k]) {
            line.push_str(
                " // TODO(import): domain candidate (return pair defaults to [net name, GND]; the ::DC value is a human call)",
            );
        }
        mc.push_str(&line);
        mc.push('\n');
    }

    mc.push_str("\n    // ---- net connections (in mct net order) ----\n");
    for (k, lines) in net_lines.iter().enumerate() {
        if lines.is_empty() {
            continue;
        }
        mc.push_str(&format!(
            "\n    // {}. net {} ({} pins)\n",
            k,
            display[k],
            d.nets[k].pins.len()
        ));
        if let Some(orig) = &net_renamed[k] {
            mc.push_str(&format!("    // renamed: {orig} -> {}\n", net_idents[k]));
        }
        for l in lines {
            mc.push_str(&format!("    {l}\n"));
        }
    }
    mc.push_str("}\n");

    Rendered { main: mc, todo_count: todos.len() }
}

/// Power-domain candidate per the plan's shape: V-prefixed labels that are not
/// return-path names. Output is TODO comments only — never a live `::DC`.
fn is_domain_candidate(display: &str) -> bool {
    let up = display.to_ascii_uppercase();
    display.starts_with('V')
        && !up.contains("GND")
        && !up.contains("VSS")
        && up != "VCOM"
        && up != "VEE"
}

/// Loose libref sniff for the "dangling two-parter" TODO only (not for inline
/// decisions — those go through `value::parse`'s whitelist).
fn is_passive_libref(libref: &str) -> bool {
    let head: String = libref
        .split('.')
        .next()
        .unwrap_or("")
        .trim()
        .chars()
        .take_while(|c| c.is_ascii_alphabetic())
        .collect::<String>()
        .to_ascii_uppercase();
    matches!(head.as_str(), "C" | "CAP" | "CAPACITOR" | "R" | "RES" | "RESISTOR" | "L" | "IND" | "INDUCTOR")
}

/// Escape `"` and `\` for a quoted partno.
fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// UTC date from the unix epoch (no chrono dependency — see Cargo.toml note).
pub fn today_utc() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0) as i64;
    let days = secs.div_euclid(86_400);
    // Howard Hinnant's civil_from_days
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = doy - (153 * mp + 2) / 5 + 1;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    let year = if month <= 2 { y + 1 } else { y };
    format!("{year:04}-{month:02}-{day:02}")
}
