# Copyright (c) 2026 MCode
# skeleton: generated by mcc import --skeleton from mct.netlist/1 (tool: schdoc, project demo)
# source: demo.SchDoc
# pin attach rate: 93.4%
# convention: anything unresolved (values, pin directions, power domains) stays a TODO(import) stub - nothing is invented; the semantic calls are human
# (net-name semantics, domain assignment, DNP/NC calls, mcpub library matching are all human work)
#
# TODO(import) summary:
#   1. U1: value 'TP4054' did not parse under the high-confidence rules -> partno stub
#   2. U2: value 'XC6206' did not parse under the high-confidence rules -> partno stub
#   3. net VCC: power-domain candidate (assumed return pair [VCC, GND]) -> the ::DC(?V) value is a human call
#   4. dangling attachment points: 1 (see the mct output's dangling section; judge NC vs missing connection per item)

# ---- class definitions (local components; directions all io, psrc/psnk never guessed) ----

component TP4054.U1
{
    partno = "TP4054"

    pins = [
        io 5 = P5
        io 2 = P2
    ]
}

component LDO.U2
{
    partno = "XC6206"

    pins = [
        io 3 = P3
        io 2 = P2
    ]
}

module main
{
    // ---- instances ----
    TP4054.U1 U1
    LDO.U2 U2

    // ---- anchors (one per referenced net; semantics and domain assignment are human) ----
    in N_1 // was: N$1
    in VCC // TODO(import): domain candidate (return pair defaults to [net name, GND]; the ::DC value is a human call)
    in GND
    in V5V // was: 5V
    in N_7 // was: N$7

    // ---- net connections (in mct net order) ----

    // 0. net N$1 (2 pins)
    // renamed: N$1 -> N_1
    N_1 -> U1.P5
    N_1 -> U2.P3

    // 1. net VCC (2 pins)
    VCC - C1::CAP(100nF, CAP.X7R, 25V) - GND
    VCC -> U2.P2

    // 2. net GND (3 pins)
    GND - U5V1::CAP(10uF) - V5V
    GND - R1::RES(10kΩ, ±1%) - V5V

    // 4. net N$7 (1 pins)
    // renamed: N$7 -> N_7
    N_7 -> U1.P2
}