#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the old→new diagnostic code mapping table (Phase 0 deliverable).

Input : the scan baseline (scripts/error-code-inventory.json) + manual
        semantic confirmation of every same-code-reused site.
Output: scripts/error-code-mapping.json

The new numbering follows mcd/doc/mcc-error-code-unification-plan.md §3.2
(4-digit, thousands+hundreds = pipeline stage / semantic cluster).
Every old code is retired; same-code-different-semantic sites are split.
"""
import json
import os

# ---------------------------------------------------------------------------
# Entry: (old_code, site, new_code, CONST_NAME, description)
#   site: short file/semantic tag used to disambiguate same-code reuse.
#         "" means the old code maps uniformly.
#   new_code: None means "removed — never emitted" (legacy register fiction).
# ---------------------------------------------------------------------------
M = [
    # ═══ Pass1a: duplicate definitions (1000-1049) ═══
    (1001, "mc_code.rs", 1001, "DUP_INTERFACE",
     "An interface with the same name already exists in this file."),
    (1002, "mc_code.rs", 1002, "DUP_COMPONENT",
     "A component with the same name already exists in this file."),
    (1004, "mc_code.rs", 1003, "DUP_ENUM",
     "An enum with the same name already exists in this file."),
    (1503, "mc_code.rs", 1004, "DUP_MODULE",
     "A module with the same name already exists in this file."),
    (1505, "mc_code.rs", 1005, "DUP_DEFINE",
     "A define with the same name already exists in this file."),

    # ═══ Pass1a: definition structure / CMIE load (1050-1099) ═══
    (501, "mc_code.rs", 1051, "DEF_ALREADY_EXISTS",
     "Definition already exists."),
    (503, "mc_code.rs", 1052, "CMIE_LOAD_REJECTED",
     "The declaration is a define or an unexpected type and cannot be loaded as a CMIE."),
    (1001, "mc_inst.rs", 1053, "INST_MISSING_SUBNODE",
     "Missing subnode in an instance declaration."),
    (1001, "mc_pins/mod.rs", 1054, "PINS_MISSING_SUBNODE",
     "Missing subnode in a pins declaration."),
    (1001, "mc_enum.rs:subnodes", 1055, "ENUM_MISSING_SUBNODES",
     "Enum definition is missing its subnodes."),
    (1001, "mc_enum.rs:name", 1056, "ENUM_MISSING_NAME",
     "Enum definition is missing its name."),
    (1001, "mc_enum.rs:name-ids", 1057, "ENUM_MISSING_NAME_IDS",
     "Enum definition is missing its name ids."),
    (1001, "mc_enum.rs:values", 1058, "ENUM_MISSING_VALUES",
     "Enum definition is missing its values."),
    (1002, "mc_inst.rs", 1059, "MALFORMED_IOTYPE",
     "Malformed IO type node in a pin/port declaration."),

    # ═══ Pass1b: use statements (2000-2049) ═══
    (402, "mc_use.rs", 2001, "USE_PATH_INVALID",
     "Invalid path in a use statement."),
    (403, "mc_use.rs:prefix", 2002, "USE_URI_PREFIX_INVALID",
     "Unrecognized URI prefix — expected $, /, ./, or ../."),
    (403, "mc_use.rs:target", 2003, "USE_TARGET_NOT_FOUND",
     "The use target file was not found."),
    (2001, "imports.rs", 2004, "USE_SELF_IMPORT",
     "File imports itself via a use statement."),
    (2002, "imports.rs", 2005, "USE_ALIAS_COLLISION",
     "A use alias collides with an existing name."),
    (2003, "imports.rs", 2006, "USE_VERSIONED_TARGET_NOT_FOUND",
     "The versioned use target file was not found."),
    (2004, "imports.rs", 2007, "USE_IMPORT_SYMBOL_NOT_FOUND",
     "A symbol listed in use import(...) was not found in the target file."),
    (2005, "imports.rs", 2008, "USE_REEXPORT_SYMBOL_NOT_FOUND",
     "A symbol in pub use import(...) was not found and cannot be re-exported."),
    (3201, "body.rs:uri", 2009, "USE_MIXED_PATH_SEPARATORS",
     "A use path mixes '.' and '/' separators."),

    # ═══ Pass1b: use-stage diagnostics (2050-2079) ═══
    (800, "mc_code.rs", 2051, "USE_DEP_NOT_DECLARED",
     "Use of an undeclared dependency — add it to project.toml [dependencies] or load via --lib."),
    (800, "mc_code.rs", 2052, "USE_LIB_NOT_FOUND",
     "The library is not installed in the system root — install it with `mcc lib install` or load it with --lib."),
    (801, "mc_code.rs", 2061, "USE_SYMBOL_CONFLICT",
     "An imported symbol conflicts with an existing name."),
    (804, "mc_code.rs", 2071, "USE_IMPORTED_NOT_FOUND",
     "The imported symbol was not found in the target file."),

    # ═══ Pass1b: parser / AST messages (2080-2119) ═══
    # C parser codes — renumber the MCD_* macros in src/ast/c/astdef.h.
    (1000, "astdef.h", 2080, "PARSER_SYNTAX_ERROR",
     "Generic syntax error."),
    (1002, "astdef.h", 2081, "PARSER_TOP_INVALID",
     "Invalid top-level declaration."),
    (1003, "astdef.h", 2082, "PARSER_CLAUSE_INVALID",
     "Invalid clause in a body."),
    (1004, "astdef.h", 2083, "PARSER_PIN_INVALID",
     "Invalid pin declaration."),
    (1005, "astdef.h", 2084, "PARSER_PIN_ID_NOT_CONST",
     "Pin ID must be a constant integer, not an expression."),
    (1006, "astdef.h", 2085, "PARSER_PIN_NAME_NOT_CONST",
     "Pin name must be a constant identifier, not an expression."),
    (1007, "astdef.h", 2086, "PARSER_NET_NOT_PORT",
     "Net endpoint must be a port/label, not a literal."),
    (1008, "astdef.h", 2087, "PARSER_NET_INVALID",
     "Invalid net/connection expression."),
    (1009, "astdef.h", 2088, "PARSER_CONDS_INVALID",
     "Invalid if/else condition block."),
    (1010, "astdef.h", 2089, "PARSER_ROLE_INVALID",
     "Invalid role block."),
    (1011, "astdef.h", 2090, "PARSER_FUNC_INVALID",
     "Invalid function definition."),
    (1012, "astdef.h", 2091, "PARSER_PINS_INVALID",
     "Invalid pins declaration."),
    (1013, "astdef.h", 2092, "PARSER_USE_INVALID",
     "Invalid import statement."),
    (1014, "astdef.h", 2093, "PARSER_CONDBLOCK_INVALID",
     "Invalid condition body."),
    (1015, "astdef.h", 2094, "PARSER_DECLAREB_INVALID",
     "Invalid instance declaration (:: syntax)."),
    (1016, "astdef.h", 2095, "PARSER_BODY_INVALID",
     "Invalid body."),
    (1017, "astdef.h", 2096, "PARSER_JUDGE_INVALID",
     "Invalid condition expression."),
    (1018, "astdef.h", 2097, "PARSER_PARD_INVALID",
     "Invalid parameter declaration."),
    (1019, "astdef.h", 2098, "PARSER_URI_INVALID",
     "Invalid import path."),
    (1020, "astdef.h", 2099, "PARSER_PHRASES_INVALID",
     "Invalid expression list."),
    (1021, "astdef.h", 2100, "PARSER_OPDS_INVALID",
     "Invalid operand list."),
    (1022, "astdef.h", 2101, "PARSER_PARAMS_INVALID",
     "Invalid parameter list."),
    (1023, "astdef.h", 2102, "PARSER_PARDS_INVALID",
     "Invalid parameter declaration list."),
    (1024, "astdef.h", 2103, "PARSER_ATTR_VALUES_INVALID",
     "Invalid attribute value list."),
    (1025, "astdef.h", 2104, "PARSER_ATTR_LINES_INVALID",
     "Invalid attribute line list."),
    (1026, "astdef.h", 2105, "PARSER_PINS_NAMES_INVALID",
     "Invalid pin name list."),
    (1027, "astdef.h", 2106, "PARSER_INSTS_INVALID",
     "Invalid instance list."),
    (1028, "astdef.h", 2107, "PARSER_CONDS_ELIFS_INVALID",
     "Invalid else-if chain."),
    (1029, "astdef.h", 2108, "PARSER_IDSS_INVALID",
     "Invalid identifier list."),
    (1030, "astdef.h", 2109, "PARSER_LEVELS_INVALID",
     "Invalid path in import."),
    (1031, "astdef.h", 2110, "PARSER_PHRASE_INVALID",
     "Invalid expression."),
    (1101, "astdef.h", 2111, "PARSER_SINGLE_OR",
     "Single '|' used as a binary operator outside a pin context."),
    (1102, "astdef.h", 2112, "PARSER_PLUSMINUS",
     "'±' used as a binary operator outside a tolerance context."),
    (1103, "astdef.h", 2113, "PARSER_TRANSPOSE_ON_LITERAL",
     "Transpose (') on a literal has no effect."),
    (1104, "astdef.h", 2114, "PARSER_CARET_ON_LITERAL",
     "Caret (^) on a literal has no effect."),
    (1105, "astdef.h", 2115, "PARSER_EMPTY_BODY",
     "Empty body — no clauses defined."),
    (1106, "astdef.h", 2116, "PARSER_EMPTY_PINS",
     "Empty pins declaration."),
    # AST FFI layer (ast_node.rs)
    (201, "ast_node.rs", 2117, "AST_NODE_EMPTY",
     "AST node is null/empty where a value was expected."),
    (205, "ast_node.rs", 2117, "AST_NODE_EMPTY",
     "AST node is null/empty where a value was expected."),
    (203, "ast_node.rs", 2118, "AST_UTF8_ERROR",
     "AST node contains invalid UTF-8 data."),
    (206, "ast_node.rs", 2118, "AST_UTF8_ERROR",
     "AST node contains invalid UTF-8 data."),
    (207, "ast_node.rs", 2119, "AST_TYPE_MISMATCH",
     "AST node has an unexpected type."),

    # ═══ Pass1b: name resolution (2120-2199) ═══
    (1101, "mc_ids.rs:no-nodes", 2121, "NAME_IDS_NO_NODES",
     "IDS has no nodes."),
    (1101, "mc_ids.rs/mc_opd.rs/mc_inst.rs", 2122, "NAME_MISSING_SUBNODE",
     "Missing subnode in a name reference."),
    (1101, "mc_phrase.rs:declare", 2123, "NAME_DECLARE_PARSE_FAILED",
     "Failed to parse a DECLARE node."),
    (1101, "mc_ids.rs:square-vector", 2124, "NAME_SQUARE_VECTOR_MISSING_SUBNODE",
     "Missing subnode for a square vector."),
    (1102, "mc_ids.rs:range", 2125, "NAME_RANGE_SIDE_FAILED",
     "Failed to process a side of a range."),
    (1106, "mc_phrase.rs:label-fallback", 2126, "NAME_DEF_NOT_FOUND_LABEL_FALLBACK",
     "Definition not found; falling back to a label."),
    (1100, "mc_phrase.rs", 2127, "NAME_ID_EXTRACT_FAILED",
     "Failed to extract ID/IDA data from a node."),
    (1107, "", 2171, "NOT_SUPPORTED_YET",
     "This syntax is parsed but not yet supported by the semantic layer; the declaration is ignored."),
    # Removed: never-emitted legacy register constants (errcodes.rs fiction)
    (1504, "errcodes.rs", None, "NAME_DEFINITION_NOT_FOUND", "removed — never emitted"),
    (1105, "errcodes.rs", None, "NAME_INSTANCE_NOT_FOUND", "removed — never emitted"),
    (1106, "errcodes.rs", None, "NAME_IDS_RESOLVE_FAILED", "removed — never emitted"),

    # ═══ Pass1c: component definition — pins (3000-3049) ═══
    (1103, "mc_pins/mod.rs:trace", 3001, "PIN_ID_NAME_MISMATCH",
     "Pin ID and pin name do not match."),
    (1103, "mc_pins/mod.rs:error", 3002, "PIN_ID_COUNT_ERROR",
     "Pin id count error."),
    (2106, "mc_pins/mod.rs", 3003, "PINS_PLUS_WITHOUT_BASE",
     "pins += is used without a prior pins = definition."),
    (1201, "mc_pins/mod.rs", 3004, "PIN_NAME_TYPE_UNSUPPORTED",
     "Pin name has an unsupported type."),
    (1204, "mc_pins/mod.rs", 3004, "PIN_NAME_TYPE_UNSUPPORTED",
     "Pin name has an unsupported type."),
    (1203, "mc_pins/mod.rs/mc_inst.rs", 3005, "PIN_NAME_COUNT_ERROR",
     "Pin/port name count error."),
    (1200, "mc_inst.rs", 3006, "PORT_NAME_TYPE_UNSUPPORTED",
     "Port name has an unsupported type."),
    (1202, "mc_inst.rs", 3007, "PORT_NAME_COUNT_ERROR",
     "Port name count error."),
    (1205, "mc_pins/mod.rs", 3008, "PIN_EXPR_TYPE_MISMATCH",
     "Pin expression node has an unexpected type."),
    # Pass1c: component definition — attributes (3020-3039)
    (601, "mc_attr.rs", 3021, "ATTR_TYPE_MISMATCH",
     "Attribute node type mismatch."),
    (603, "mc_attr.rs", 3022, "ATTR_TYPE_NOT_SUPPORTED",
     "Attribute type is not supported."),
    # Pass1c: component definition — units / values (3040-3059)
    (301, "mc_kvs.rs", 3041, "KVS_VALUE_TYPE_INVALID",
     "Invalid value type in a KVS node."),
    (302, "mc_uval.rs:type", 3042, "UVAL_VALUE_TYPE_INVALID",
     "Invalid unit value type."),
    (303, "mc_uval.rs:data", 3043, "UVAL_DATA_NODE_INVALID",
     "Invalid unit value data node."),
    (304, "mc_uval.rs:unit", 3044, "UVAL_UNIT_INVALID",
     "Invalid unit."),
    (304, "mc_uval.rs:value", 3045, "UVAL_VALUE_INVALID",
     "Invalid unit value."),
    (305, "mc_uval.rs", 3046, "UVAL_UNIT_UNSUPPORTED",
     "The unit is not supported."),
    (1800, "mc_uval.rs", 3047, "UVAL_MISSING_DATA_NODE",
     "Missing unit value data node."),
    (1803, "mc_uval.rs", 3048, "UVAL_FORMAT_INVALID",
     "Invalid unit value or float format."),
    (1804, "mc_uval.rs", 3049, "UVAL_UNIT_VARIANT_INVALID",
     "Invalid unit variant (angle, charge, magnetic flux, slew rate, ...)."),

    # ═══ Pass1c: module body (3050-3099) ═══
    (804, "module/mod.rs", 3051, "MODULE_MISSING_SUBNODE",
     "Missing subnode in a module body clause."),
    (801, "module/mod.rs:pins", 3052, "MODULE_PINS_UNSUPPORTED",
     "Module does not support PINS directly; use in/out/io declarations."),
    (801, "module/mod.rs:role", 3053, "MODULE_ROLE_UNSUPPORTED",
     "Module does not support role definition."),
    (803, "module/mod.rs", 3054, "MODULE_PARAM_TYPE_UNEXPECTED",
     "Unexpected type in a module parameter."),
    (1501, "mc_code.rs", 3071, "MODULE_METHOD_NOT_FOUND",
     "Function was not found in the class."),
    (1402, "module/mod.rs", 3081, "UNEXPECTED_CLAUSE_TYPE",
     "Unexpected clause type in a module body."),

    # ═══ Pass1c: params / functions (3100-3149) ═══
    (1300, "mc_func.rs/module/mod.rs", 3101, "FUNC_EMPTY_NET",
     "Empty net in a function or module body."),
    (1303, "mc_paramd.rs/mc_pins/mod.rs", 3103, "PARAM_DECLARE_INVALID",
     "Invalid parameter declaration node."),
    (1304, "mc_paramd.rs/mc_pins/mod.rs", 3104, "PARAM_NAME_INVALID",
     "Invalid parameter name."),
    (1305, "mc_paramd.rs/mc_pins", 3105, "PARAM_SET_INVALID",
     "Invalid parameter set."),
    (1307, "mc_paramd.rs", 3106, "PARAM_UVAL_INVALID",
     "Invalid parameter unit value."),
    (1308, "mc_uval.rs", 3107, "PARAM_CLASS_EXPECTED",
     "Expected a class in the declaration unit value."),
    (1309, "mc_uval.rs", 3108, "PARAM_INSTANCE_EXPECTED",
     "Expected an instance in the declaration unit value."),
    (1310, "mc_paramd.rs", 3109, "PARAM_NAME_EXTRACT_FAILED",
     "Failed to extract the parameter name."),
    (1301, "mc_fcall.rs", 3131, "FUNC_CALL_MISSING_NAME",
     "Missing function name in a function call."),
    (1301, "module/mod.rs", 3132, "CONN_LINE_PARSE_FAILED",
     "A connection line failed to parse."),
    (1308, "mc_func.rs", 3133, "FUNC_BODY_INVALID",
     "Invalid function body node."),
    (1309, "mc_func.rs", 3134, "FUNC_LINE_DROPPED",
     "A connection line was dropped because McPhrase::new returned None."),
    (1316, "mc_fcall.rs", 3135, "FCALL_PARSE_FAILED",
     "Function call parse failure."),
    (1305, "mc_func.rs", 3161, "FUNC_RETURN_MALFORMED",
     "Malformed return statement."),
    (1307, "mc_func.rs", 3162, "FUNC_RETURN_EXPR_INVALID",
     "Invalid return expression — expected this or a label/bus."),
    (1313, "mc_func.rs", 3163, "FUNC_MULTIPLE_RETURNS",
     "A function may have at most one return statement."),

    # ═══ Pass1c: instance declaration / reference (3150-3199) ═══
    (1003, "mc_phrase.rs", 3151, "INST_EXPR_PARSE_FAILED",
     "Failed to parse an instance in an expression context."),
    (1006, "mc_phrase.rs", 3152, "CURLY_MN_WRONG_BASE",
     "Curly-member construction requires a component or module base."),
    (1600, "mc_inst.rs", 3153, "INST_CLASS_NODE_MISSING",
     "No class node found in the instance declaration."),
    (1601, "mc_inst.rs", 3154, "INST_NODE_MISSING",
     "No instance node found."),
    (1602, "mc_inst.rs", 3155, "INST_CLASS_ID_MISSING",
     "Missing class id node."),
    (1603, "mc_inst.rs", 3156, "INST_CLASS_IDS_PARSE_FAILED",
     "Failed to parse class ids."),
    (1401, "mc_inst.rs", 3157, "INST_CLASS_UNRESOLVED",
     "Unresolved class — the library may not be loaded."),
    (1700, "mc_phrase.rs", 3171, "IFACE_MEMBER_NOT_FOUND",
     "Interface member not found in the component."),
    (1702, "mc_phrase.rs", 3172, "IFACE_CURLY_MEMBER_INVALID",
     "Cannot access interface members using curly-bracket syntax."),
    (1702, "instref.rs", 3173, "IFACE_COMPONENT_NOT_FOUND",
     "Component not found for the interface reference."),
    (1703, "mc_inst.rs", 3174, "IFACE_BUS_NOT_FOUND",
     "Interface not found for a bus reference."),
    (1704, "instref.rs", 3175, "MODULE_PORT_NOT_FOUND",
     "Port(s) not found in the module."),
    (1803, "mc_phrase.rs", 3175, "MODULE_PORT_NOT_FOUND",
     "Port not found in the module."),
    (1705, "mc_phrase.rs", 3176, "BUS_NAME_ALREADY_INSTANCE",
     "Name is already an instance; cannot create a bus with these members."),
    (1706, "instref.rs", 3177, "IFACE_PIN_NOT_FOUND",
     "Pin(s) not found in the interface."),
    (1707, "mc_pins/mod.rs", 3178, "IFACE_MEMBER_LOOKUP_FAILED",
     "Interface member lookup failed."),
    (1801, "instref.rs", 3179, "COMPONENT_PIN_NOT_FOUND",
     "Pin(s) not found in the component or interface."),
    (1802, "mc_phrase.rs", 3179, "COMPONENT_PIN_NOT_FOUND",
     "Pin not found in the component."),

    # ═══ Pass2: connection / shape (4000-4049) ═══
    (1102, "mc_phrase.rs", 4001, "CONN_TRANSPOSE_SIZE_MISMATCH",
     "Transposed connection size mismatch."),
    (1153, "mc_phrase.rs", 4001, "CONN_TRANSPOSE_SIZE_MISMATCH",
     "Transposed connection size mismatch."),
    (1106, "mc_phrase.rs:shape", 4002, "CONN_LEFT_ARROW_SHAPE_MISMATCH",
     "Shape mismatch in a <- connection."),
    (1150, "mc_phrase.rs", 4003, "CONN_CANNOT_TRANSPOSE",
     "The transpose operator is not allowed at this position."),
    (1151, "mc_phrase.rs:parallel-invalid", 4004, "CONN_PARALLEL_INVALID",
     "An instance with 3+ pins cannot directly participate in a '+' operation."),
    (1151, "mc_phrase.rs:parallel-shape", 4005, "CONN_PARALLEL_SHAPE_MISMATCH",
     "Shape mismatch in a parallel connection."),
    (1154, "mc_phrase.rs", 4006, "CONN_SERIES_INVALID",
     "An instance with 3+ pins cannot directly participate in a '-' operation."),
    (1155, "mc_phrase.rs", 4007, "CONN_SERIES_SHAPE_MISMATCH",
     "Shape mismatch in a -> connection."),
    (1110, "mc_phrase.rs:operator", 4008, "CONN_OPERATOR_UNSUPPORTED",
     "The operator is not supported in connection lines; use '+' for parallel, '-' / '->' for series."),
    (1110, "mc_phrase.rs:node-type", 4009, "PHRASE_AST_TYPE_UNEXPECTED",
     "Unexpected AST node type in a phrase."),
    (1162, "mc_phrase.rs", 4010, "CONN_NO_PORTS_COMPONENT",
     "No ports found in the component."),
    (1163, "mc_phrase.rs", 4011, "CONN_NO_PORTS_MODULE",
     "No ports found in the module."),
    (1164, "mc_phrase.rs", 4012, "CONN_NO_PORTS_INTERFACE",
     "No ports found in the interface."),
    (1168, "mc_phrase.rs", 4013, "CONN_DOT_SERIES",
     "Dot operator does not apply to a Series."),
    (1169, "mc_phrase.rs", 4014, "CONN_DOT_NODE",
     "Dot operator does not apply to a Node."),
    (1170, "mc_phrase.rs", 4015, "CONN_DOT_TRANSPOSED",
     "Dot operator does not apply to a Transposed."),
    (1171, "mc_phrase.rs", 4016, "CONN_DOT_LEAD",
     "Dot operator does not apply to a Lead."),
    (1172, "mc_phrase.rs", 4017, "CONN_DOT_GROUP",
     "Dot operator does not apply to a Group."),
    (1175, "mc_phrase.rs:endpoint", 4018, "CONN_DOT_ENDPOINT",
     "Dot operator does not apply to an Endpoint."),
    (1176, "mc_phrase.rs", 4019, "CONN_DOT_MEMBER",
     "Dot operator already applied to a Member."),
    (1173, "mc_phrase.rs", 4020, "CLOSURE_NO_OUTPUT_IFACE",
     "Closure has no output interface to access."),
    (1174, "mc_phrase.rs", 4021, "FUNCCALL_NO_RETURN_IFACE",
     "FuncCall has no return interface to access."),
    (1175, "mc_phrase.rs:member", 4022, "PHRASE_IFACE_MEMBER_NOT_FOUND",
     "Member not found in the interface."),
    (1197, "mc_phrase.rs", 4023, "CURLY_LEFT_EMPTY",
     "Curly-member construction: left member list is empty."),
    (1198, "mc_phrase.rs", 4024, "CURLY_RIGHT_EMPTY",
     "Curly-member construction: right member list is empty."),
    (1199, "mc_phrase.rs", 4025, "CURLY_NOT_BUS",
     "Cannot convert the curly-member result to a bus."),
    (1220, "mc_phrase.rs", 4026, "GROUP_BRANCH_COUNT_MISMATCH",
     "Groups with different branch counts cannot connect."),

    # ═══ Pass2: netlist heuristics (4050-4099) ═══
    (2003, "group.rs/visit.rs", 4051, "NET_MERGED_SHORT",
     "Multiple points resolve to the same node — possible short circuit (E2003)."),
    (2005, "group.rs", 4052, "NET_BUS_ORDER_MISMATCH",
     "Bus member order mismatch after sorting (E2005)."),
    (2001, "instref.rs", 4053, "SORT_HAZARD",
     "Bus pin numbers are non-monotonic; member→pin mapping may be wrong after sorting."),
    (2002, "visit.rs", 4054, "FLOATING_PLACEHOLDER",
     "A '_' placeholder could not be bound to any pin."),
    (2004, "fromblock.rs", 4055, "GHOST_PORT",
     "A net endpoint is not mapped to any box — possible unexposed module boundary port."),
    (2007, "funccall.rs", 4056, "PULLUP_DEGENERATE",
     "Pullup/pulldown degenerated into a signal-signal bridge."),
    (2006, "mc_phrase.rs:dropped-statement", 4057, "NET_DROPPED_STATEMENT",
     "A single-element square bracket expands to an unknown instance; the statement may produce no nets or constraints."),
    (2001, "mc_layout.rs", 4081, "LAYOUT_MISSING_SUBNODE",
     "Layout attribute is missing a required subnode."),
    (2002, "mc_layout.rs", 4082, "LAYOUT_TYPE_MISMATCH",
     "Layout attribute node type mismatch."),
    (2003, "mc_layout.rs", 4083, "LAYOUT_SET_MISSING_SUBNODE",
     "Layout set is missing a required subnode."),
    (2004, "mc_layout.rs", 4084, "LAYOUT_VALUES_TYPE_MISMATCH",
     "Layout values node type mismatch."),
    (2005, "mc_layout.rs", 4085, "LAYOUT_NAME_MISSING_SUBNODE",
     "Layout name is missing a required subnode."),
    (2006, "mc_layout.rs", 4086, "LAYOUT_EDGE_MISSING_SUBNODE",
     "Layout edge is missing a subnode."),
    (2007, "mc_layout.rs", 4087, "LAYOUT_EDGE_TYPE_MISMATCH",
     "Layout edge node type mismatch."),
    (2008, "mc_layout.rs", 4088, "LAYOUT_EDGE_NAME_MISSING_SUBNODE",
     "Layout edge name is missing a subnode."),
    (2009, "mc_layout.rs", 4089, "LAYOUT_VALUE_MISSING_SUBNODE",
     "Layout value is missing a subnode."),
    (2010, "mc_layout.rs", 4090, "LAYOUT_VALUE_TYPE_MISMATCH",
     "Layout value node type mismatch."),
    (2011, "mc_layout.rs", 4091, "LAYOUT_SET_SUBNODE_MISSING",
     "Layout set is missing a subnode."),
    (2012, "mc_layout.rs", 4092, "LAYOUT_EXTRA_NODES",
     "Malformed layout: unexpected extra nodes."),
    (2013, "mc_layout.rs", 4093, "LAYOUT_VALUES_MISSING_SUBNODE",
     "Layout values are missing a subnode."),
    (2014, "mc_layout.rs", 4094, "LAYOUT_CONST_MISSING_INT",
     "CONST node is missing its INT subnode."),
    (2015, "mc_layout.rs", 4095, "LAYOUT_PIN_NUMBER_PARSE",
     "Parse error in a layout pin number."),
    (2016, "mc_layout.rs", 4096, "LAYOUT_EDGE_NAME_ID_MISSING_SUBNODE",
     "Layout edge name id is missing a subnode."),
    (2017, "mc_layout.rs", 4097, "LAYOUT_EDGE_INVALID",
     "Invalid layout edge."),
    (2018, "mc_layout.rs", 4098, "LAYOUT_EDGE_NAME_NOT_ID",
     "Malformed layout: edge name is not an ID."),

    # ═══ Pass2: netlist / interface binding (4100-4149) ═══
    (3101, "nets/mod.rs", 4101, "NET_MULTI_DRIVE",
     "Net has multiple drivers — possible short circuit."),
    (3101, "interface.rs", 4102, "IFACE_PINS_NOT_ALL_BOUND",
     "Interface requires more pins than are bound to physical pins."),
    (3102, "nets/mod.rs", 4103, "NET_NO_DRIVER",
     "Net has inputs but no output/power driver."),
    (3102, "interface.rs", 4104, "IFACE_ROLE_NOT_FOUND",
     "Interface role referenced by a param does not exist in the interface."),
    (3103, "nets/mod.rs", 4105, "NET_VOLTAGE_MISMATCH",
     "Power nets with different voltages are shorted together."),
    (3103, "interface.rs", 4106, "IFACE_NOT_LOADED",
     "Interface referenced by a param is not loaded."),
    (3104, "interface.rs", 4107, "IFACE_DEPRECATED_CMIE",
     "Deprecated interface/component/param used."),
    (3105, "nets/mod.rs/interface.rs", 4108, "NET_INPUT_UNCONNECTED",
     "An input port is not connected to any net."),
    (3106, "nets/mod.rs", 4109, "NET_NC_CONNECTED",
     "An NC port is connected to a net."),
    (3107, "nets/mod.rs", 4110, "NET_OUTPUT_UNDRIVEN",
     "An output drives nothing."),
    (3108, "nets/mod.rs", 4111, "NET_BACKFEED_RISK",
     "Net has both an output and a power supply — backfeed risk."),
    (3109, "nets/mod.rs", 4112, "NET_INSTANCE_UNCONNECTED",
     "Instance has no pins connected to any net."),
    (3110, "nets/mod.rs", 4113, "NET_OUTPUTS_NO_INPUT",
     "Net has outputs and power but no input."),
    (3111, "nets/mod.rs", 4114, "NET_MODULE_PORT_UNCONNECTED",
     "Module port is not connected to any net."),
    (3112, "nets/mod.rs", 4115, "NET_DANGLING_ENDPOINT",
     "Net has only one endpoint — possible dangling connection."),
    (3113, "nets/mod.rs", 4116, "NET_PARTIAL_CONNECTION",
     "Only some of the instance pins are connected."),
    (3114, "nets/mod.rs", 4117, "NET_BIDIR_UNCONNECTED",
     "A bidirectional port is not connected to any net."),
    (3199, "nets/mod.rs", 4118, "NET_POWER_NET_COUNT",
     "Design has many power nets; review for consolidation."),

    # ═══ Pass2: instantiation checks (4150-4199) ═══
    (940, "phases.rs", 4151, "INST_ARG_NO_FORMAL_PORT",
     "Instance argument has no formal port to bind."),
    (944, "funccall.rs/iterated.rs/line.rs", 4152, "INST_METHOD_FALLBACK",
     "Instance method could not be resolved; passed through instead."),
    # ── missed by the initial scan: record_warning/record_error sites ──
    (900, "mod.rs", 4153, "INST_IFACE_INSTANTIATE_FAILED",
     "Interface instantiation failed."),
    (901, "phases.rs", 4154, "INST_SUBMODULE_INSTANTIATE_FAILED",
     "Sub-module instantiation failed."),
    (910, "line.rs:skip-failed-class", 4155, "INST_LINE_SKIP_FAILED_CLASS",
     "Line references a component class whose instantiation failed; the whole line is skipped."),
    (910, "phases.rs:line-failed", 4156, "INST_LINE_PARSE_FAILED",
     "A connection line failed to expand."),
    (911, "line.rs:builtin-twopin", 4157, "INST_BUILTIN_TWOPIN_EXPAND_FAILED",
     "Expanded builtin two-pin pair failed."),
    (911, "line.rs:member", 4158, "INST_MEMBER_PROCESS_FAILED",
     "A member of a connection line failed to process."),
    (912, "line.rs", 4159, "INST_ADJACENT_CONNECT_FAILED",
     "Connection between adjacent members of a series failed."),
    (913, "line.rs:shunt", 4160, "INST_SHUNT_PROCESS_FAILED",
     "A `.Cap(_)` shunt member failed to process."),
    (913, "mod.rs:func-line", 4161, "INST_FUNC_BODY_LINE_FAILED",
     "A module-level function body line failed."),
    (914, "line.rs", 4162, "INST_LANE_FUNCCALL_FAILED",
     "Failed to instantiate a FuncCall during lane-by-lane wiring."),
    (915, "line.rs", 4163, "INST_LANE_TRANSPOSED_FAILED",
     "Failed to instantiate a Transposed member during lane-by-lane wiring."),
    (920, "group.rs", 4164, "CONN_SHAPE_MISMATCH_TRUNCATED",
     "Connection shape mismatch; truncated to the smaller side."),
    (921, "line.rs", 4165, "CONN_PARALLEL_DIM_MISMATCH",
     "Parallel '+' operand dimension mismatch; operand merged into the anchor's left net."),
    (922, "group.rs", 4166, "CONN_GROUP_SHAPE_MISMATCH",
     "Group connection shape mismatch; truncated by branch count."),
    (930, "fcallinst.rs:input-pins", 4167, "INST_INPUT_PIN_COUNT_MISMATCH",
     "Component input pin count mismatch in a function call."),
    (931, "fcallinst.rs:output-pins", 4168, "INST_OUTPUT_PIN_COUNT_MISMATCH",
     "Component output pin count mismatch in a function call."),
    (932, "fcallinst.rs", 4169, "INST_INLINE_MODULE_FAILED",
     "Inline module instantiation failed."),
    (933, "fcallinst.rs:input-ports", 4170, "INST_INPUT_PORT_COUNT_MISMATCH",
     "Module input port count mismatch in a function call."),
    (934, "fcallinst.rs:output-ports", 4171, "INST_OUTPUT_PORT_COUNT_MISMATCH",
     "Module output port count mismatch in a function call."),
    (942, "phases.rs:power-unbound", 4172, "INST_POWER_PORT_UNBOUND",
     "Sub-module DC power port is never connected (missing power argument?)."),
    (942, "phases.rs:ctor-line", 4173, "INST_CTOR_BODY_LINE_FAILED",
     "A constructor function body line failed."),
    (941, "phases.rs:ctor-bind", 4174, "INST_CTOR_PARAM_BIND_FAILED",
     "Constructor parameter binding failed."),
    (940, "line.rs:method-fallback", 4152, "INST_METHOD_FALLBACK",
     "Instance method could not be resolved; passed through instead."),

    # ═══ Pass3: duplicate validation (5000-5049) ═══
    (2100, "duplicate.rs", 5001, "DUP_CMIE_CROSS_FILE",
     "Same name defined in another file (cross-file duplicate)."),
    (2151, "dupwithin.rs", 5002, "DUP_WITHIN",
     "Duplicate definition within the same declaration."),
    (2152, "dupwithin.rs", 5003, "DUP_ENUM_VALUE",
     "Enum value appears more than once in the enum."),

    # ═══ Pass3: naming / style (5050-5099) ═══
    (2201, "naming.rs/style.rs", 5051, "NAME_COMPONENT_LOWERCASE",
     "Component name starts with lowercase; convention is UPPER_SNAKE."),
    (2203, "extra.rs", 5052, "NAME_PORT_SHADOWS_CMIE",
     "Port name shadows a library CMIE name."),
    (2205, "naming.rs", 5053, "NAME_PIN_MIXED_CONVENTION",
     "Pins use mixed naming conventions."),
    (2206, "naming.rs", 5054, "NAME_INSTANCE_SINGLE_CHAR",
     "Instance name is a single character."),
    (2207, "naming.rs", 5055, "NAME_PIN_NUMERIC",
     "Pin name is purely numeric."),
    (2208, "naming.rs", 5056, "NAME_PORT_INST_SHADOWS_CMIE",
     "Port/instance name shadows a library CMIE name."),
    (2209, "naming.rs", 5057, "NAME_PARAM_SHADOWS_CMIE",
     "Parameter name shadows a library CMIE name."),

    # ═══ Pass3: reference integrity (5100-5149) ═══
    (2301, "refs.rs", 5101, "SPEC_KEY_UNDECLARED_PARAM",
     "Spec key references a parameter that is not declared."),
    (2302, "refs.rs", 5102, "REF_INTEGRITY",
     "Reference integrity violation."),
    (2303, "refs.rs", 5103, "FUNC_PARAMS_NO_BODY",
     "Function has parameters but no body (empty implementation)."),
    (2307, "exprs.rs", 5104, "EXPR_PINS_X_UNDEFINED",
     "pins.X references an undefined pin name."),

    # ═══ Pass3: ports / pins (5150-5199) ═══
    (2401, "ports.rs", 5151, "INST_DECLARED_MULTIPLE",
     "Instance is declared more than once in the module."),
    (2402, "ports.rs", 5152, "PORT_DUPLICATE_NAME",
     "Duplicate port name in the module — ambiguous."),
    (2402, "mc_pins/mod.rs", 5153, "NOT_AN_INTERFACE",
     "The class is a component/module/enum, not an interface."),
    (2410, "ports.rs", 5154, "NAME_PARAM_AND_INSTANCE",
     "Name is both a value parameter and an instance."),
    (3201, "pins.rs", 5155, "PIN_UNCONNECTED",
     "Pin is not connected to any net."),
    (3202, "pins.rs", 5156, "PIN_CONFLICTING_OPTIONS",
     "Pin uses conflicting option names."),
    (3202, "body.rs", 5157, "FUNC_RETURN_OUTSIDE_FUNCTION",
     "Return statement used outside a function."),
    (3203, "body.rs", 5158, "FUNC_RETURN_LITERAL_INVALID",
     "Return statement specifies a literal instead of an endpoint."),
    (3204, "body.rs", 5159, "INST_EMPTY_TABLE",
     "Empty instance table in a [] :: TYPE declaration."),
    (3205, "body.rs", 5160, "INST_THIS_TYPE",
     "this :: TYPE declaration is not allowed."),
    (3206, "body.rs", 5161, "FUNC_ROLE_AS_ARG",
     "Role used as a function-call argument."),
    (3207, "body.rs", 5162, "MODULE_PORT_UNUSED",
     "Module port is declared but never connected."),
    (3208, "body.rs", 5163, "COND_SINGLE_BINARY",
     "Condition compares against a single binary value."),

    # ═══ Pass3: functions / roles / defaults (5200-5249) ═══
    (2501, "extra.rs", 5201, "ENUM_SINGLE_VALUE",
     "Enum has only one value."),
    (2505, "extra.rs", 5202, "PARAM_INT_DEFAULT_STRING",
     "Integer param has a string default."),
    (2506, "extra.rs", 5203, "PARAM_STRING_DEFAULT_NUMERIC",
     "String param has a numeric-looking default."),
    (2507, "extra.rs", 5204, "PARAM_UV_DEFAULT_NO_UNIT",
     "Unit-value param default has no unit suffix (e.g. '5V')."),
    (2513, "extra.rs:float", 5205, "PARAM_FLOAT_DEFAULT_INVALID",
     "Param has an invalid float default."),
    (2513, "extra.rs:negative", 5206, "PARAM_NEGATIVE_DEFAULT",
     "Integer param default is negative."),

    # ═══ Pass3: definition structure M-series (5250-5299) ═══
    (2601, "extra.rs", 5251, "PARAM_RESERVED_KEYWORD",
     "Parameter uses a reserved keyword."),
    (2602, "extra.rs", 5252, "FUNC_EMPTY_BODY",
     "Function has an empty body."),
    (2603, "extra.rs", 5253, "COMPONENT_EMPTY",
     "Component has no params, pins, attributes, or functions."),
    (2604, "extra.rs", 5254, "COMPONENT_NO_PINS",
     "Component has no pin definitions."),
    (2605, "extra.rs", 5255, "INTERFACE_EMPTY",
     "Interface has no pins or roles."),
    (2606, "extra.rs", 5256, "INST_CLASS_NOT_LOADED",
     "Instance references a class that is not loaded."),
    (2607, "extra.rs", 5257, "COMPONENT_MIXED_CASE",
     "Component name uses mixed case; convention is UPPER_SNAKE."),
    (2609, "extra.rs", 5258, "BUS_DUPLICATE_MEMBER",
     "Bus has a duplicate member."),
    (2610, "extra.rs", 5259, "COMPONENT_DUPLICATE_FUNC_BODY",
     "Component has functions with the same body."),
    (2611, "extra.rs", 5260, "DEFINE_NO_ATTRS",
     "Define has no attributes."),
    (2612, "extra.rs", 5261, "DEFINE_NON_ATTR_CLAUSE",
     "Define contains a non-attribute clause."),
    (2613, "extra.rs", 5262, "IFACE_PIN_COUNT_MISMATCH",
     "Interface expects more pins than are bound."),
    (2614, "extra.rs", 5263, "FUNC_SHARES_NAME_WITH_PORT",
     "Function shares its name with a port/param."),
    (2615, "extra.rs", 5264, "NET_BOTH_OUTPUTS",
     "Net connects two outputs."),
    (2616, "extra.rs", 5265, "FUNC_INLINE_BODY_LITERAL_ARG",
     "Inline function body literal used as a call argument."),
    (2617, "extra.rs", 5266, "FUNC_PARAMS_UNUSED",
     "Function declares parameters it never uses."),
    (2618, "extra.rs", 5267, "SPEC_KEY_DUPLICATE",
     "Spec key appears more than once."),

    # ═══ Pass3: .int class checks (5300-5349) ═══
    (2701, "defs.rs", 5301, "DEF_AMBIGUOUS_NAME",
     "Same name used for different definition kinds."),
    (2702, "defs.rs", 5302, "DEF_REF_NOT_LOADED",
     "Definition references a class that is not loaded."),
    (2703, "defs.rs", 5303, "COMPONENT_INT_SUFFIX",
     "Component has an unconventional '.int' suffix."),
    (2704, "defs.rs", 5304, "ENUM_INT_SUFFIX",
     "Enum has an unconventional '.int' suffix."),

    # ═══ Pass3: instance / attribute checks (5350-5399) ═══
    (2801, "attrs.rs", 5351, "ATTR_RESERVED_KEYWORD",
     "Attribute uses a reserved keyword."),
    (2801, "insts.rs", 5352, "INST_ARG_COUNT_MISMATCH",
     "Instance passes more/fewer args than the class declares."),
    (2802, "attrs.rs/insts.rs", 5353, "ROLE_EMPTY_BODY",
     "Role has an empty body."),
    (2803, "insts.rs", 5354, "ROLE_NAME_SHADOWS",
     "Role shares its name with a parameter or pin/port."),
    (2804, "attrs.rs/insts.rs", 5355, "ATTR_NESTING_TOO_DEEP",
     "Attribute nesting depth exceeds 16."),
    (2805, "attrs.rs/insts.rs", 5356, "ATTR_PIN_GROUP_UNDEFINED",
     "Attribute references an undefined pin group, or role used outside a component."),
    (2806, "attrs.rs/insts.rs", 5357, "PINS_PLUS_AND_PINS_CONFLICT",
     "Component mixes pins = and pins.X = attributes, or uses a non-constant default."),

    # ═══ Pass3: enum / expression checks (5400-5449) ═══
    (2901, "enums.rs", 5401, "ENUM_DUPLICATE_VALUE",
     "Enum has a duplicate value."),
    (2902, "enums.rs", 5402, "ENUM_MEMBER_DOT",
     "Enum member contains a dot."),
    (2903, "enums.rs", 5403, "ENUM_MEMBER_LEADING_DIGIT",
     "Enum member starts with a digit."),
    (2904, "enums.rs", 5404, "ENUM_MEMBER_RESERVED",
     "Enum member is a reserved keyword."),
    (2905, "enums.rs:self-ref", 5412, "ATTR_SELF_REFERENTIAL",
     "Attribute value equals its own key; likely a copy-paste mistake."),
    (2905, "exprs.rs:inf", 5405, "ATTR_INFINITE_FLOAT",
     "Attribute has an infinite float value."),
    (2905, "exprs.rs:large", 5406, "ATTR_LARGE_INT",
     "Attribute has a suspiciously large integer value."),
    (2906, "enums.rs", 5407, "RANGE_REVERSED",
     "Range appears reversed; did you mean the opposite order?"),
    (2906, "exprs.rs", 5407, "RANGE_REVERSED",
     "Range appears reversed; did you mean the opposite order?"),
    (2907, "exprs.rs", 5408, "RANGE_SINGLE_ELEMENT",
     "Range expands to a single element."),
    (2908, "exprs.rs", 5409, "IDX_MULTIPLE_SLICE_SPEC",
     "IDX key has multiple slice specifications."),
    (2901, "exprs.rs", 5410, "EXPR_THIS_TOP_LEVEL",
     "'this' used in a top-level net line; it is only valid inside instance/function contexts."),
    (2902, "exprs.rs", 5411, "EXPR_PLACEHOLDER_ONLY",
     "Net connects only to '_' placeholder; the connection has no effect."),

    # ═══ Pass3: condition blocks (5450-5499) ═══
    (3001, "conds.rs", 5451, "COND_EMPTY_BODY",
     "Conditional block has an empty body."),
    (3002, "conds.rs", 5452, "COND_IF_WITHOUT_ELSE",
     "if without a matching else."),
    (3003, "conds.rs", 5453, "PIN_NC_COMPONENT_LEVEL",
     "NC pin used at component level."),
    (3004, "conds.rs", 5454, "POWER_PIN_NO_VOLTAGE",
     "Power pin has no voltage attribute."),
    (3005, "conds.rs", 5455, "PIN_IO_MIX_IN_OUT",
     "Pin mixes In and Out IO types."),
    (3006, "conds.rs", 5456, "PIN_IO_MIX_OUTPUT_POWER",
     "Pin mixes Output and Power IO types."),
    (3007, "conds.rs", 5457, "PIN_IO_MIX_ANALOG_POWER",
     "Pin mixes Analog and Power IO types."),
    (3008, "conds.rs", 5458, "PARAM_PIN_NAME_SHADOW",
     "Parameter shares its name with a pin."),
    (3009, "conds.rs", 5459, "MODULE_STUB",
     "Module is a stub."),

    # ═══ Pass3: hardware checks (5500-5549) ═══
    (3301, "hw.rs", 5501, "HW_POWER_PINS_EXCESS",
     "Too many power pins."),
    (3302, "hw.rs", 5502, "HW_PIN_NUMBER_GAP",
     "Pin numbers have gaps."),
    (3303, "hw.rs", 5503, "HW_PIN_COUNT_HIGH",
     "Pin count is unusually high."),
    (3304, "hw.rs", 5504, "HW_ZERO_PINS_WITH_PARAMS",
     "Component has zero pins but parameter attributes."),
    (3305, "hw.rs", 5505, "HW_NC_PINS_CONTIGUOUS",
     "Consecutive NC pins."),
    (3306, "hw.rs", 5506, "HW_IFACE_ROLE_UNBOUND",
     "Interface role is never bound."),
    (3307, "hw.rs", 5507, "HW_ALL_SAME_IO_TYPE",
     "All pins have the same IO type."),
    (3308, "hw.rs", 5508, "HW_MISSING_NAME_ATTR",
     "Missing 'name' attribute."),
    (3309, "hw.rs", 5509, "HW_NAME_WITHOUT_DESC",
     "Has a name but no description."),
    (3310, "hw.rs", 5510, "HW_FUNC_PARAM_SHADOWS_PIN",
     "Function parameter shadows a pin name."),
    (3311, "hw.rs", 5511, "HW_IFACE_NEVER_BOUND",
     "Interface is defined but never bound."),

    # ═══ Pass3: type / unit compatibility (5550-5599) ═══
    (3401, "types.rs", 5551, "TYPE_CLOSURE_FREE_VAR",
     "Closure references a free variable that is not declared."),
    (3402, "types.rs", 5552, "TYPE_INCOMPATIBLE",
     "Incompatible types or unit types."),

    # ═══ Pass3: global diagnostics (5600-5649) ═══
    (1402, "lib.rs:unused", 5641, "UNUSED_PARAM_OR_PORT",
     "Parameter or port is declared but never used."),
    (1405, "module/mod.rs", 5642, "PORT_NEVER_USED",
     "Port is declared but never used in any net connection."),
    (1403, "lib.rs", 5643, "UNTYPED_PARAM",
     "Parameter has no inferred type."),

    # ═══ ERC (6000-6099) ═══
    (5001, "", 6001, "ERC_SINGLE_POINT_NET",
     "Single-point net: only one connection."),
    (5002, "", 6002, "ERC_UNCONNECTED_PORT",
     "Unconnected port: not connected to any net."),
    (5003, "", 6003, "ERC_MULTI_DRIVE_NET",
     "Multi-drive net."),
    (5004, "", 6004, "ERC_FLOATING_NET",
     "Floating net."),
]

# ---------------------------------------------------------------------------
# Validate & emit
# ---------------------------------------------------------------------------
def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, "error-code-mapping.json")

    seen_new = {}
    entries = []
    for old, site, new, name, desc in M:
        if new is None:
            entries.append({"old": old, "site": site, "new": None,
                            "name": name, "desc": desc})
            continue
        if new in seen_new:
            prev = seen_new[new]
            if prev[3] != name:
                raise SystemExit(f"new code {new} reused with different names: "
                                 f"{prev[3]} vs {name}")
        seen_new[new] = (old, site, new, name, desc)
        entries.append({"old": old, "site": site, "new": new,
                        "name": name, "desc": desc})

    # Per-old-code aggregation (for phase-3 replacement)
    by_old = {}
    for e in entries:
        by_old.setdefault(str(e["old"]), []).append(e)

    doc = {
        "generated_by": "scripts/build-error-code-mapping.py",
        "plan": "mcd/doc/mcc-error-code-unification-plan.md §3.2",
        "note": "All old diagnostic codes are retired; same-code-different-semantic "
                "sites are split. 'new: null' entries were legacy registry constants "
                "never emitted — removed.",
        "total_old_sites": len(entries),
        "total_new_codes": len(seen_new),
        "mapping": sorted(entries, key=lambda e: (e["old"], e["site"])),
        "by_old": {k: sorted(v, key=lambda e: (e["new"] or 0)) for k, v in sorted(by_old.items(), key=lambda kv: int(kv[0]))},
    }
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
    print(f"wrote {out_path}")
    print(f"  old sites: {len(entries)}  new codes: {len(seen_new)}")

if __name__ == "__main__":
    main()
