#!/usr/bin/env python3
"""Declaration index for src/: flatten every top-level declaration in each .rs
into a single greppable list of "path#Lline  kind name" lines.

Usage:
    python3 scripts/src-index.py [--root .] [--write SRC-INDEX.md]

Criteria (fixed; do not change without updating SRC-INDEX.md):
    Files       = `src/**/*.rs`.
    Declarations = fn / struct / enum / trait / union / mod / const / static /
                   type / impl at the start of a line (indentation allowed),
                   optionally preceded by `pub`, `pub(crate)`, `default`,
                   `unsafe`, `async`. Indented declarations are NOT excluded --
                   methods inside impl blocks are exactly what is most often
                   being looked up.
    Line number = 1-based, the physical line of the declaration in the file.

**Each line stands alone** (`path#Lline  kind name`) -- that is the core
convention of this index: one grep hit yields the path, the line, and the name
at once, with no need to scroll back for context. The `#L` form is used rather
than `path:line` so as not to trip the bare-reference rule in
scripts/check-links.py (same as doc-index.py in the mcd repo).

**This is an approximate index, not a compiler**: regex matching misses
macro-generated declarations and declarations split across lines (`pub fn`
followed by the name), and does not understand `#[cfg]`. Use it to LOCATE, then
confirm with `mcc show` / `rg`.

Exit code: 0 = no oversized files; 2 = oversized files exist that must be read
with care (see the "high risk" section).
"""

import argparse
import os
import re
import sys

SRC_ROOT = "src"
SNAPSHOT = "SRC-INDEX.md"

# A file larger than this is listed as high risk: reading it whole is expensive
# and the read-guard hook will refuse it.
BIG_BYTES = 100 * 1024

DECL_RX = re.compile(
    r"^\s*"
    r"(?:pub(?:\s*\([^)]*\))?\s+)?"
    r"(?:default\s+)?"
    r"(?:unsafe\s+)?"
    r"(?:async\s+)?"
    r"(fn|struct|enum|trait|union|mod|const|static|type)\s+"
    r"([A-Za-z_]\w*)"
)

# The target of an impl is not a single identifier (`impl<T> Foo<T> for Bar`),
# so take everything up to the `{`.
IMPL_RX = re.compile(r"^\s*impl\b([^{]*)\{")


def read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except (OSError, UnicodeDecodeError):
        return ""


def src_files(root):
    """[(absolute path, path relative to src/)], in stable order."""
    d = os.path.join(root, SRC_ROOT)
    out = []
    for dp, dn, fns in os.walk(d):
        dn[:] = sorted(x for x in dn if not x.startswith("."))
        for fn in sorted(fns):
            if fn.endswith(".rs"):
                full = os.path.join(dp, fn)
                out.append((full, os.path.relpath(full, d)))
    return sorted(out, key=lambda t: t[1])


def declarations(path):
    """[(line number, kind, name)]."""
    out = []
    for i, line in enumerate(read(path).split("\n"), 1):
        stripped = line.lstrip()
        # Skip comment lines outright, to avoid noise like `// fn foo`.
        if stripped.startswith(("//", "/*", "*")):
            continue
        m = DECL_RX.match(line)
        if m:
            out.append((i, m.group(1), m.group(2)))
            continue
        m = IMPL_RX.match(line)
        if m:
            target = " ".join(m.group(1).split())
            if target:
                out.append((i, "impl", target))
    return out


def render(root):
    files = src_files(root)
    L = []
    L.append("# SRC-INDEX.md -- declaration index for src/ (generated; do not edit)")
    L.append("")
    L.append("Generated by `scripts/src-index.py`. **Do not read this file whole** --")
    L.append("use Grep to locate: ")
    L.append("")
    L.append("```sh")
    L.append("grep -n 'fn resolve_gate' SRC-INDEX.md")
    L.append("grep -n 'impl .*McIds' SRC-INDEX.md")
    L.append("```")
    L.append("")
    L.append("Each line stands alone, in the form `path#Lline  kind name` (the path is")
    L.append("relative to `src/`). Go straight to a precise read; do not read the whole")
    L.append("source file:")
    L.append("")
    L.append("```")
    L.append("Read(file_path=\"src/semantic/basic/mc_phrase.rs\", offset=412, limit=80)")
    L.append("```")
    L.append("")
    L.append("**This index is approximate**: the regex does not recognise macro-generated")
    L.append("declarations or declarations split across lines, and does not look at")
    L.append("`#[cfg]`. Use it to locate, then confirm with `rg` or `mcc show`.")
    L.append("")
    L.append("Regenerate: `python3 scripts/src-index.py --write SRC-INDEX.md`")
    L.append("")

    entries, big = [], []
    for full, rel in files:
        size = os.path.getsize(full)
        decls = declarations(full)
        if size > BIG_BYTES:
            big.append((rel, size, len(decls)))
        entries.append((rel, size, decls))

    L.append("## High risk: do not read these whole")
    L.append("")
    if big:
        L.append("These files **must** be located with Grep first, then read with")
        L.append("`offset`/`limit`. The read-guard hook refuses to read them without a")
        L.append("range (threshold 40KB).")
        L.append("")
        L.append("| File | Size | Declarations |")
        L.append("|---|---|---|")
        for rel, size, nd in sorted(big, key=lambda t: -t[1]):
            L.append("| `%s` | %d KB | %d |" % (rel, size // 1024, nd))
    else:
        L.append("None.")
    L.append("")

    L.append("## Modules")
    L.append("")
    L.append("| Directory | Files | Size |")
    L.append("|---|---|---|")
    bydir = {}
    for rel, size, _d in entries:
        top = rel.split(os.sep)[0] if os.sep in rel else "(root)"
        n, s = bydir.get(top, (0, 0))
        bydir[top] = (n + 1, s + size)
    for top in sorted(bydir):
        n, s = bydir[top]
        L.append("| `%s/` | %d | %d KB |" % (top, n, s // 1024))
    L.append("")

    L.append("## Declaration index")
    L.append("")
    n_decl = 0
    for rel, _size, decls in entries:
        for lineno, kind, name in decls:
            L.append("%s#L%d  %s %s" % (rel, lineno, kind, name))
            n_decl += 1
    L.append("")
    L.append("---")
    L.append("")
    L.append("%d files, %d declarations." % (len(files), n_decl))

    return "\n".join(L), len(big)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--write", nargs="?", const=SNAPSHOT,
                    help="write the index (default %s)" % SNAPSHOT)
    args = ap.parse_args()
    text, n_big = render(args.root)
    if args.write:
        out = os.path.join(args.root, args.write)
        os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print("wrote %s" % out)
    else:
        print(text)
    print("src-index: %d oversized file(s)" % n_big, file=sys.stderr)
    return 2 if n_big else 0


if __name__ == "__main__":
    sys.exit(main())
